# Insertion Sort implementation in Python
# Generated by Copilot
def insertion_sort(arr):
    if arr is None:
        return []
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr

# Example usage:
# print(insertion_sort([5, 2, 9, 1, 5, 6]))
# Generated by Copilot
