// Selection Sort implementation in Java
// Generated by Copilot
public class SelectionSort {
    public static void selectionSort(int[] arr) {
        int n = arr.length;
        for (int i = 0; i < n - 1; i++) {
            int min_idx = i;
            for (int j = i + 1; j < n; j++) {
                if (arr[j] < arr[min_idx]) {
                    min_idx = j;
                }
            }
            int temp = arr[min_idx];
            arr[min_idx] = arr[i];
            arr[i] = temp;
        }
    }

    // Example usage:
    // public static void main(String[] args) {
    //     int[] arr = {5, 2, 9, 1, 5, 6};
    //     selectionSort(arr);
    //     System.out.println(java.util.Arrays.toString(arr));
    // }
}
// Generated by Copilot
